---
ansible_host: 10.1.100.134
physical_interfaces:
  - name: GigabitEthernet2
    description: Physical Interface to lab_internal vSwitch
    enabled: True
  - name: Loopback0
    description: Loopback Interface for BGP
    enabled: True

logical_interfaces:
  - name: GigabitEthernet0/2.2010
    ipv4:
      - address: 10.20.1.38/30
  - name: GigabitEthernet0/2.2011
    ipv4:
      - address: 10.20.1.42/30
  - name: GigabitEthernet0/2.2012
    ipv4:
      - address: 10.20.1.45/30
  - name: Loopback0
    ipv4:
      - address: 10.20.3.1/32
