ansible_host: 10.1.100.139
physical_interfaces:
  - name: ge-0/0/0
    description: Physical Interface to lab_internal vSwitch
    enabled: True
  - name: ge-0/0/1
    description: Physical Interface to branch_switch_ext vSwitch
    enabled: True
  - name: lo0
    description: Loopback Interface for Protocols
    enabled: True

logical_interfaces:
  - name: ge-0/0/0
    ipv4:
      - address: 10.20.1.46/30
    unit: 2012
  - name: ge-0/0/1
    ipv4:
      - address: 10.20.2.1/24
    unit: 0
  - name: lo0
    ipv4:
      - address: 10.20.3.11/32
    unit: 0
