---
ansible_host: 10.1.100.132
physical_interfaces:
  - name: GigabitEthernet2
    description: Physical Interface to lab_internal vSwitch
    enabled: True
  - name: GigabitEthernet2.2006
    description: Subinterface to nalabeos1 
    enabled: True
  - name: GigabitEthernet2.2007
    description: Subinterface to nalabvmx1vcp
    enabled: True
  - name: Loopback0
    description: Loopback Interface for Protocols
    enabled: True

logical_interfaces:
  - name: GigabitEthernet2
    ipv4:
      - address: 10.20.1.21
        mask: 255.255.255.252
    unit: 2006
  - name: GigabitEthernet2
    ipv4:
      - address: 10.20.1.26
        mask: 255.255.255.252
    unit: 2007
  - name: Loopback0
    ipv4:
      - address: 10.20.3.5
        mask: 255.255.255.255
