---
ansible_host: 10.1.100.134
physical_interfaces:
  - name: GigabitEthernet2
    description: Physical Interface to lab_internal vSwitch
    enabled: True
  - name: Loopback0
    description: Loopback Interface for BGP
    enabled: True

logical_interfaces:
  - name: GigabitEthernet0/2
    ipv4:
      - address: 10.20.1.38
        mask: 255.255.255.252
    unit: 2010
  - name: GigabitEthernet0/2
    ipv4:
      - address: 10.20.1.42
        mask: 255.255.255.252
    unit: 2011
  - name: GigabitEthernet0/2
    ipv4:
      - address: 10.20.1.45/30
        mask: 255.255.255.252
    unit: 2012
  - name: Loopback0
    ipv4:
      - address: 10.20.3.1
        mask: 255.255.255.255
