---
ansible_host: 10.1.100.132
physical_interfaces:
  - name: GigabitEthernet2
    description: Physical Interface to lab_internal vSwitch
    enabled: True
  - name: Loopback0
    description: Loopback Interface for Protocols
    enabled: True

logical_interfaces:
  - name: GigabitEthernet0/2.2006
    ipv4:
      - address: 10.20.1.21/30
  - name: GigabitEthernet0/2.2007
    ipv4:
      - address: 10.20.1.26/30
  - name: Loopback0
    ipv4:
      - address: 10.20.3.5/32
